# Generated by Django 5.0.1 on 2024-02-03 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=8)),
                ('setor', models.CharField(choices=[('oficina', 'oficina'), ('showroom', 'showroom')], max_length=30)),
                ('veiculo', models.CharField(max_length=50)),
                ('valor_veiculo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantidade_veiculos', models.IntegerField(max_length=5)),
            ],
        ),
    ]
